"""
TrustFL Schemas Package.

Common Pydantic data models for messages, round states, proof payloads, and metadata.
"""

from trustfl_schemas import (
    VALID_TRANSITIONS,
    ArtifactId,
    BlockchainEventType,
    BlockchainRecord,
    ClientId,
    ClientIdentity,
    ClientRole,
    ClientStatus,
    ClientUpdate,
    EntityIdentifierPayload,
    EvaluationMetrics,
    FederationId,
    InvalidStateTransitionError,
    ModelArtifact,
    ModelMetadata,
    ModelVersionId,
    ProofMetadata,
    ProofType,
    RoundId,
    RoundState,
    StorageProtocol,
    TrainingMetrics,
    TrainingRound,
    UpdateId,
    assert_valid_transition,
    validate_artifact_id,
    validate_client_id,
    validate_federation_id,
    validate_model_version_id,
    validate_round_id,
    validate_update_id,
)

__version__ = "0.1.0"

__all__ = [
    "FederationId",
    "RoundId",
    "ClientId",
    "ModelVersionId",
    "UpdateId",
    "ArtifactId",
    "EntityIdentifierPayload",
    "validate_federation_id",
    "validate_round_id",
    "validate_client_id",
    "validate_model_version_id",
    "validate_update_id",
    "validate_artifact_id",
    "RoundState",
    "VALID_TRANSITIONS",
    "InvalidStateTransitionError",
    "assert_valid_transition",
    "ClientIdentity",
    "ClientRole",
    "ClientStatus",
    "ProofMetadata",
    "ProofType",
    "StorageProtocol",
    "ModelArtifact",
    "ModelMetadata",
    "TrainingMetrics",
    "EvaluationMetrics",
    "ClientUpdate",
    "BlockchainEventType",
    "BlockchainRecord",
    "TrainingRound",
]
