/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as updateRegistrySol from './UpdateRegistry.sol/index.js';
export { ClientRegistry__factory } from './ClientRegistry__factory.js';
export { TrainingRoundRegistry__factory } from './TrainingRoundRegistry__factory.js';