"""Initial migration

Revision ID: 3c1cda7650c5
Revises:
Create Date: 2026-09-29 22:27:37.684401

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3c1cda7650c5'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blockchain_transactions',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('tx_hash', sa.String(length=128), nullable=True),
    sa.Column('contract_name', sa.String(length=64), nullable=False),
    sa.Column('function_name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('entity_id', sa.String(length=128), nullable=True),
    sa.Column('entity_type', sa.String(length=32), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bctx_entity_id', 'blockchain_transactions', ['entity_id'], unique=False)
    op.create_table('federations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'COMPLETED', 'ARCHIVED', name='federationstatus'), nullable=False),
    sa.Column('min_clients', sa.Integer(), nullable=False),
    sa.Column('max_rounds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_artifacts',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('federation_id', sa.String(length=64), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.String(length=64), nullable=True),
    sa.Column('uri', sa.Text(), nullable=False),
    sa.Column('sha256_hash', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('model_version', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_artifacts_federation_id', 'model_artifacts', ['federation_id'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('federation_id', sa.String(length=64), nullable=False),
    sa.Column('public_key_b64', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('capabilities', sa.Text(), nullable=True),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['federation_id'], ['federations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_clients_federation_id', 'clients', ['federation_id'], unique=False)
    op.create_table('rounds',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('federation_id', sa.String(length=64), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'ACTIVE', 'AGGREGATING', 'FINALIZED', 'FAILED', name='roundstatus'), nullable=False),
    sa.Column('model_version', sa.String(length=128), nullable=True),
    sa.Column('global_model_artifact_id', sa.String(length=128), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['federation_id'], ['federations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_rounds_federation_id', 'rounds', ['federation_id'], unique=False)
    op.create_table('updates',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('round_id', sa.String(length=64), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'VERIFIED', 'AGGREGATED', 'REJECTED', name='updatestatus'), nullable=False),
    sa.Column('artifact_id', sa.String(length=128), nullable=True),
    sa.Column('artifact_hash', sa.String(length=128), nullable=True),
    sa.Column('nonce', sa.String(length=128), nullable=True),
    sa.Column('num_examples', sa.Integer(), nullable=True),
    sa.Column('loss', sa.Float(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['round_id'], ['rounds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_updates_client_id', 'updates', ['client_id'], unique=False)
    op.create_index('ix_updates_round_id', 'updates', ['round_id'], unique=False)
    op.create_table('proofs',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('update_id', sa.String(length=128), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('federation_id', sa.String(length=64), nullable=False),
    sa.Column('round_id', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=128), nullable=True),
    sa.Column('public_commitment', sa.Text(), nullable=False),
    sa.Column('protocol', sa.String(length=64), nullable=False),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['update_id'], ['updates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_proofs_update_id', 'proofs', ['update_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_proofs_update_id', table_name='proofs')
    op.drop_table('proofs')
    op.drop_index('ix_updates_round_id', table_name='updates')
    op.drop_index('ix_updates_client_id', table_name='updates')
    op.drop_table('updates')
    op.drop_index('ix_rounds_federation_id', table_name='rounds')
    op.drop_table('rounds')
    op.drop_index('ix_clients_federation_id', table_name='clients')
    op.drop_table('clients')
    op.drop_index('ix_artifacts_federation_id', table_name='model_artifacts')
    op.drop_table('model_artifacts')
    op.drop_table('federations')
    op.drop_index('ix_bctx_entity_id', table_name='blockchain_transactions')
    op.drop_table('blockchain_transactions')
    # ### end Alembic commands ###
