/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IClientRegistry } from './IClientRegistry.js';
export type { ITrainingRoundRegistry } from './ITrainingRoundRegistry.js';
export type { UpdateRegistry } from './UpdateRegistry.js';