/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'TrainingRoundRegistry', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.TrainingRoundRegistry__factory>
getContractFactory(name: 'ClientRegistry', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ClientRegistry__factory>
getContractFactory(name: 'IClientRegistry', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IClientRegistry__factory>
getContractFactory(name: 'ITrainingRoundRegistry', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ITrainingRoundRegistry__factory>
getContractFactory(name: 'UpdateRegistry', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.UpdateRegistry__factory>

  getContractAt(name: 'TrainingRoundRegistry', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.TrainingRoundRegistry>
getContractAt(name: 'ClientRegistry', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ClientRegistry>
getContractAt(name: 'IClientRegistry', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IClientRegistry>
getContractAt(name: 'ITrainingRoundRegistry', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ITrainingRoundRegistry>
getContractAt(name: 'UpdateRegistry', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.UpdateRegistry>

  deployContract(name: 'TrainingRoundRegistry', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TrainingRoundRegistry>
deployContract(name: 'ClientRegistry', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ClientRegistry>
deployContract(name: 'IClientRegistry', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IClientRegistry>
deployContract(name: 'ITrainingRoundRegistry', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ITrainingRoundRegistry>
deployContract(name: 'UpdateRegistry', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.UpdateRegistry>

  deployContract(name: 'TrainingRoundRegistry', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TrainingRoundRegistry>
deployContract(name: 'ClientRegistry', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ClientRegistry>
deployContract(name: 'IClientRegistry', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IClientRegistry>
deployContract(name: 'ITrainingRoundRegistry', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ITrainingRoundRegistry>
deployContract(name: 'UpdateRegistry', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.UpdateRegistry>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  