/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as updateRegistrySol from './UpdateRegistry.sol/index.js';
export type { updateRegistrySol };
export type { ClientRegistry } from './ClientRegistry.js';
export type { TrainingRoundRegistry } from './TrainingRoundRegistry.js';
export * as factories from './factories/index.js';
export { TrainingRoundRegistry__factory } from './factories/TrainingRoundRegistry__factory.js';
export type { IClientRegistry } from './UpdateRegistry.sol/IClientRegistry.js';
export { IClientRegistry__factory } from './factories/UpdateRegistry.sol/IClientRegistry__factory.js';
export type { ITrainingRoundRegistry } from './UpdateRegistry.sol/ITrainingRoundRegistry.js';
export { ITrainingRoundRegistry__factory } from './factories/UpdateRegistry.sol/ITrainingRoundRegistry__factory.js';
export type { UpdateRegistry } from './UpdateRegistry.sol/UpdateRegistry.js';
export { UpdateRegistry__factory } from './factories/UpdateRegistry.sol/UpdateRegistry__factory.js';
export { ClientRegistry__factory } from './factories/ClientRegistry__factory.js';