/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace TrainingRoundRegistry {
      
    export type TrainingRoundStruct = {globalModelVersion: string, status: BigNumberish}

    export type TrainingRoundStructOutput = [globalModelVersion: string, status: bigint] & {globalModelVersion: string, status: bigint }
  
    }

  export interface TrainingRoundRegistryInterface extends Interface {
    getFunction(nameOrSignature: "COORDINATOR_ROLE" | "DEFAULT_ADMIN_ROLE" | "activateRound" | "createRound" | "finalizeRound" | "getRoleAdmin" | "getRound" | "grantRole" | "hasRole" | "isRoundActive" | "renounceRole" | "revokeRole" | "supportsInterface"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "RoleAdminChanged" | "RoleGranted" | "RoleRevoked" | "RoundActivated" | "RoundCreated" | "RoundFinalized"): EventFragment;

    encodeFunctionData(functionFragment: 'COORDINATOR_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'DEFAULT_ADMIN_ROLE', values?: undefined): string;
encodeFunctionData(functionFragment: 'activateRound', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createRound', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'finalizeRound', values: [BigNumberish, string]): string;
encodeFunctionData(functionFragment: 'getRoleAdmin', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getRound', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'grantRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'hasRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'isRoundActive', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'renounceRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'revokeRole', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'supportsInterface', values: [BytesLike]): string;

    decodeFunctionResult(functionFragment: 'COORDINATOR_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DEFAULT_ADMIN_ROLE', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'activateRound', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createRound', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'finalizeRound', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRoleAdmin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getRound', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'grantRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hasRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isRoundActive', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'revokeRole', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'supportsInterface', data: BytesLike): Result;
  }

  
    export namespace RoleAdminChangedEvent {
      export type InputTuple = [role: BytesLike, previousAdminRole: BytesLike, newAdminRole: BytesLike];
      export type OutputTuple = [role: string, previousAdminRole: string, newAdminRole: string];
      export interface OutputObject {role: string, previousAdminRole: string, newAdminRole: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleGrantedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoleRevokedEvent {
      export type InputTuple = [role: BytesLike, account: AddressLike, sender: AddressLike];
      export type OutputTuple = [role: string, account: string, sender: string];
      export interface OutputObject {role: string, account: string, sender: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoundActivatedEvent {
      export type InputTuple = [roundId: BigNumberish];
      export type OutputTuple = [roundId: bigint];
      export interface OutputObject {roundId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoundCreatedEvent {
      export type InputTuple = [roundId: BigNumberish, globalModelVersion: string];
      export type OutputTuple = [roundId: bigint, globalModelVersion: string];
      export interface OutputObject {roundId: bigint, globalModelVersion: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RoundFinalizedEvent {
      export type InputTuple = [roundId: BigNumberish, newGlobalModelVersion: string];
      export type OutputTuple = [roundId: bigint, newGlobalModelVersion: string];
      export interface OutputObject {roundId: bigint, newGlobalModelVersion: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface TrainingRoundRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): TrainingRoundRegistry;
    waitForDeployment(): Promise<this>;

    interface: TrainingRoundRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    COORDINATOR_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    DEFAULT_ADMIN_ROLE: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    activateRound: TypedContractMethod<
      [roundId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    createRound: TypedContractMethod<
      [roundId: BigNumberish, globalModelVersion: string, ],
      [void],
      'nonpayable'
    >
    

    
    finalizeRound: TypedContractMethod<
      [roundId: BigNumberish, newGlobalModelVersion: string, ],
      [void],
      'nonpayable'
    >
    

    
    getRoleAdmin: TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >
    

    
    getRound: TypedContractMethod<
      [roundId: BigNumberish, ],
      [TrainingRoundRegistry.TrainingRoundStructOutput],
      'view'
    >
    

    
    grantRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    hasRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    isRoundActive: TypedContractMethod<
      [roundId: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    renounceRole: TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    revokeRole: TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    supportsInterface: TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'COORDINATOR_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'DEFAULT_ADMIN_ROLE'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'activateRound'): TypedContractMethod<
      [roundId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createRound'): TypedContractMethod<
      [roundId: BigNumberish, globalModelVersion: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'finalizeRound'): TypedContractMethod<
      [roundId: BigNumberish, newGlobalModelVersion: string, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getRoleAdmin'): TypedContractMethod<
      [role: BytesLike, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getRound'): TypedContractMethod<
      [roundId: BigNumberish, ],
      [TrainingRoundRegistry.TrainingRoundStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'grantRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'hasRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isRoundActive'): TypedContractMethod<
      [roundId: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'renounceRole'): TypedContractMethod<
      [role: BytesLike, callerConfirmation: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'revokeRole'): TypedContractMethod<
      [role: BytesLike, account: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'supportsInterface'): TypedContractMethod<
      [interfaceId: BytesLike, ],
      [boolean],
      'view'
    >;

    getEvent(key: 'RoleAdminChanged'): TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
getEvent(key: 'RoleGranted'): TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
getEvent(key: 'RoleRevoked'): TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
getEvent(key: 'RoundActivated'): TypedContractEvent<RoundActivatedEvent.InputTuple, RoundActivatedEvent.OutputTuple, RoundActivatedEvent.OutputObject>;
getEvent(key: 'RoundCreated'): TypedContractEvent<RoundCreatedEvent.InputTuple, RoundCreatedEvent.OutputTuple, RoundCreatedEvent.OutputObject>;
getEvent(key: 'RoundFinalized'): TypedContractEvent<RoundFinalizedEvent.InputTuple, RoundFinalizedEvent.OutputTuple, RoundFinalizedEvent.OutputObject>;

    filters: {
      
      'RoleAdminChanged(bytes32,bytes32,bytes32)': TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
      RoleAdminChanged: TypedContractEvent<RoleAdminChangedEvent.InputTuple, RoleAdminChangedEvent.OutputTuple, RoleAdminChangedEvent.OutputObject>;
    

      'RoleGranted(bytes32,address,address)': TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
      RoleGranted: TypedContractEvent<RoleGrantedEvent.InputTuple, RoleGrantedEvent.OutputTuple, RoleGrantedEvent.OutputObject>;
    

      'RoleRevoked(bytes32,address,address)': TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
      RoleRevoked: TypedContractEvent<RoleRevokedEvent.InputTuple, RoleRevokedEvent.OutputTuple, RoleRevokedEvent.OutputObject>;
    

      'RoundActivated(uint256)': TypedContractEvent<RoundActivatedEvent.InputTuple, RoundActivatedEvent.OutputTuple, RoundActivatedEvent.OutputObject>;
      RoundActivated: TypedContractEvent<RoundActivatedEvent.InputTuple, RoundActivatedEvent.OutputTuple, RoundActivatedEvent.OutputObject>;
    

      'RoundCreated(uint256,string)': TypedContractEvent<RoundCreatedEvent.InputTuple, RoundCreatedEvent.OutputTuple, RoundCreatedEvent.OutputObject>;
      RoundCreated: TypedContractEvent<RoundCreatedEvent.InputTuple, RoundCreatedEvent.OutputTuple, RoundCreatedEvent.OutputObject>;
    

      'RoundFinalized(uint256,string)': TypedContractEvent<RoundFinalizedEvent.InputTuple, RoundFinalizedEvent.OutputTuple, RoundFinalizedEvent.OutputObject>;
      RoundFinalized: TypedContractEvent<RoundFinalizedEvent.InputTuple, RoundFinalizedEvent.OutputTuple, RoundFinalizedEvent.OutputObject>;
    
    };
  }