/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IClientRegistry, IClientRegistryInterface } from "../../UpdateRegistry.sol/IClientRegistry.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "string",
        "name": "clientId",
        "type": "string"
      }
    ],
    "name": "isClientActive",
    "outputs": [
      {
        "internalType": "bool",
        "name": "",
        "type": "bool"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IClientRegistry__factory {
    static readonly abi = _abi;
    static createInterface(): IClientRegistryInterface {
      return new Interface(_abi) as IClientRegistryInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IClientRegistry {
      return new Contract(address, _abi, runner) as unknown as IClientRegistry;
    }
  }
  