/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IClientRegistry__factory } from './IClientRegistry__factory.js';
export { ITrainingRoundRegistry__factory } from './ITrainingRoundRegistry__factory.js';
export { UpdateRegistry__factory } from './UpdateRegistry__factory.js';